import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import AppSidebar from "@/components/AppSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import PageWrapper from "@/components/PageWrapper";

const poppins = Poppins({
  // style: 'normal',
  weight: "400",
  subsets: ['latin'],
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: "Annoor Group Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-sans antialiased bg-stone-100`}
      >
        <SidebarProvider>
        <AppSidebar />
        <PageWrapper>
          {children}
        </PageWrapper>
        </SidebarProvider>
      </body>
    </html>
  );
}
