export const recentlyJoinedEmployees = [
  {
    id: 1,
    name: "Kumudini Paj",
    role: "Project Manager",
    department: "Construction",
    email: "amit.sharma@example.com",
    status: "Permanent",
  },
  {
    id: 2,
    name: "Vairab Santon",
    role: "HR Executive",
    department: "HR",
    email: "neha.verma@example.com",
    status: "On Leave",
  },
  {
    id: 3,
    name: "Chitini Basak",
    role: "Civil Engineer",
    department: "Engineering",
    email: "rajesh.kumar@example.com",
    status: "Permanent",
  },
  {
    id: 4,
    name: "Chaitanya Verma",
    role: "Full Stack Developer",
    department: "Software Engineering",
    email: "rajesh.kumar@example.com",
    status: "Contract",
  },
  {
      id: 5,
      name: "Jashro Ross",
      role: "Frontend Developer",
      department: "Software Engineering",
      email: "rajesh.kumar@example.com",
      status: "Permanent",
    },
    {
      id: 6,
      name: "Amok Sharma",
      role: "Java Developer",
      department: "Software Engineering",
      email: "rajesh.kumar@example.com",
      status: "Contract",
    },
  {
    id: 7,
    name: "Munir Hasaan",
    role: "Backend Developer",
    department: "Software Engineering",
    email: "rajesh.kumar@example.com",
    status: "Permanent",
  },
];

export const allemployees = [
  {
    id: 'EMP001',
    name: 'Navi Midan',
    email: 'navi.midan@company.com',
    role: 'Frontend Developer',
    department: 'Engineering',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/woman.png',
    joinedOn: '2025-06-15',
  },
  {
    id: 'EMP002',
    name: 'Priya Mehta',
    email: 'priya.mehta@company.com',
    role: 'HR Manager',
    department: 'Human Resources',
    phone: '+91 00000 00000',
    status: 'On Leave',
    avatar: '/man.png',
    joinedOn: '2024-11-10',
  },
  {
    id: 'EMP003',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/woman.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP004',
    name: 'Empoli Sarkar',
    email: 'empoli.sarkar@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/man.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP005',
    name: 'Erun Barman',
    email: 'erun.barman@company.com',
    role: 'UI/UX Designer',
    department: 'Full Stack Developer',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/girl.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP006',
    name: 'Balak Aman',
    email: 'balak.aman@company.com',
    role: 'Frontend Developer',
    department: 'Software Enginnering',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP007',
    name: 'Sahim Jatt',
    email: 'sahim.jatt@company.com',
    role: 'MERN Stack Developer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP008',
    name: 'Moaben Bose',
    email: 'moaben.bose@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/man.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP009',
    name: 'Jika Fob',
    email: 'jika.fob@company.com',
    role: 'Backend Developer',
    department: 'Technology',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/girl.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP010',
    name: 'Robar Bobb',
    email: 'robar.bobb@company.com',
    role: 'Java Developer',
    department: 'Technology',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP011',
    name: 'Sobar Sinha',
    email: 'sobar.sinha@company.com',
    role: 'Andriod Developer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'On Leave',
    avatar: '/girl.png',
    joinedOn: '2025-07-07',
  },
  {
    id: 'EMP012',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP013',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'Android Developer',
    department: 'Software Enginnering',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/woman.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP014',
    name: 'Pradatya Nuky',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/man.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP015',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'Talent Accuisition',
    department: 'Human Resource',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP016',
    name: 'Nabin Ferg',
    email: 'arjun.kapoor@company.com',
    role: 'Dot-Net Developer',
    department: 'Software Engineering',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/woman.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP017',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'On Leave',
    avatar: '/woman.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP018',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'Senior Data Analyst',
    department: 'Data',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/man.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP019',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP020',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'Data Analyst',
    department: 'Data',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP021',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/man.png',
    joinedOn: '2025-30-11',
  },
  {
    id: 'EMP022',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'Data Scientist',
    department: 'Data',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/woman.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP023',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/woman.png',
    joinedOn: '2025-09-02',
  },
  {
    id: 'EMP024',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'Security Engineer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/woman.png',
    joinedOn: '2025-05-04',
  },
  {
    id: 'EMP025',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/man.png',
    joinedOn: '2025-17-08',
  },
  {
    id: 'EMP026',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-27-10',
  },
  {
    id: 'EMP027',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP028',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/man.png',
    joinedOn: '2025-15-01',
  },
  {
    id: 'EMP029',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-12-01',
  },
  {
    id: 'EMP030',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/girl.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP031',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/man.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP032',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/man.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP033',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/girl.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP034',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/woman.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP035',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/man.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP036',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP037',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/woman.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP038',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP039',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/woman.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP040',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/man.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP041',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/woman.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP042',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/man.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP043',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/woman.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP044',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/girl.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP045',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP046',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP047',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP048',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/boy.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP049',
    name: 'Arjun Kapoor',
    email: 'arjun.kapoor@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/girl.png',
    joinedOn: '2025-07-01',
  },
  {
    id: 'EMP050',
    name: 'Naibu Ray',
    email: 'naibu.ray@company.com',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 00000 00000',
    status: 'Active',
    avatar: '/woman.png',
    joinedOn: '2025-07-01',
  },
];
